### ISSUE TITLE
Problem in using module with node v7.4.0 (npm v4.0.5)

### ISSUE THREAD

**Issue by dimikhan** [alexeypetrushin/synchronize#54]
I could successfully install and use this module with node v4.1.2. But last week I have have upgraded my node to v7.4.0 (I understand that's a huge upgrade with a single move, but I just thought to have the latest one). Then I can not use this module anymore. The app I could run earlier is erroring out as below. Interestingly it is searching the fibers module at the root of node_modules where as as per this module it should be present (and is present) within synchronize/node_modules. 

**c:\workspace_PL\PL_PACreation>node app.js
## There is an issue with `node-fibers` ##
`c:\workspace_PL\PL_PACreation\node_modules\synchronize\node_modules\fibers\bin\win32-x64-51\fibers.node` is missing.

Try running this to fix the issue: C:\Program Files\nodejs\node.exe c:\workspace_PL\PL_PACreation\node_modules\synchronize\node_modules\fibers/build
c:\workspace_PL\PL_PACreation\node_modules\synchronize\node_modules\fibers\fibers.js:20
        throw new Error('Missing binary. See message above.');
        ^

Error: Missing binary. See message above.
    at Object.<anonymous> (c:\workspace_PL\PL_PACreation\node_modules\synchronize\node_modules\fibers\fibers.js:20:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\workspace_PL\PL_PACreation\node_modules\synchronize\sync.js:3:13)
    at Module._compile (module.js:571:32)

c:\workspace_PL\PL_PACreation>cd ..
c:\workspace_PL>cd test
c:\workspace_PL\test>npm install synchronize
> fibers@1.0.15 install c:\workspace_PL\test\node_modules\fibers
> node build.js || nodejs build.js**

**Comment by bradvogel** [comment]
This looks like an issue with dependency node-fibers. Can you file over there?

**Comment by brenley** [comment]
Ran into the same issue; as a temporary workaround I uninstalled `node-fibers` and then just ran `npm install node-fibers` within the synchronize `node_modules` directory and that allowed me to move forward.

**Comment by dimikhan** [comment]
@brenley Thank you. Actually I saw, the reason for this error is that when it runs with node v4.1.2 it expects the fibers.node in **fibers\bin\win32-x64-46** and when it runs with node v7.4.0 it expects the fibers.node in **fibers\bin\win32-x64-51**.
When I installed synchronize module, the dependent fibers module did not installed with **win32-x64-51** folder (it has only this ***-48). Not sure if it is a problem with fibers installation or I am installing it incorrectly. Howvever, I am going to raise this into fibers module. Thanks @bradvogel for your suggestion as well.
